# Changes to the .Github subfolder
Github:
  - '.github/**'

# Any file within the config subfolder
Config:
  - 'config/**'

# Changes to a .dmm or anything in the _map subfolder
Map Edit:
  - '**/*.dmm'
  - '_maps/**'

# Any changes to .ogg files are marked as sound
Sound:
  - '**/*.ogg'

# Tools
Tools:
  - 'tools/**'

# Any .dmi changes
Sprites:
  - 'talestation_modules/icons/**'

# Upstream (code) mirror
Upstream Code:
  - 'code/**'

# Upstream (sprite) mirror
Upstream Sprites:
  - 'icons/**'
