# Changes to the .github subfolder
GitHub:
- changed-files:
  - any-glob-to-any-file: '.github/**'

# Changes to any file in the config folder
Config:
  - 'config/**'

# Changes to any .dmm
Map Edit:
- changed-files:
  - any-glob-to-any-file: '**/*.dmm'

# Changes to any .dmi
Sprites:
- changed-files:
  - any-glob-to-any-file: '**/*.dmi'

# Changes made in the tools folder
Tools:
- changed-files:
  - any-glob-to-any-file: 'tools/**'
