# Changes to the .Github subfolder
Github:
  - '.github/**'

# Any file within the config subfolder
Config:
  - 'config/**'

# Changes to a .dmm or anything in the _map subfolder
Map Edit:
  - '**/*.dmm'
  - '_maps/**'

# Tools
Tools:
  - 'tools/**'
